#!/bin/bash

# update & upgrade
echo update & upgrade -----------------------------------------------------------------------------------
sudo apt update -y
sudo apt upgrade -y


# Set up Docker's apt repository
echo Setting up docker -----------------------------------------------------------------------------------
# Add Docker's official GPG key:
# Add Docker's official GPG key:
sudo apt-get update
sudo apt-get install ca-certificates curl
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
sudo chmod a+r /etc/apt/keyrings/docker.asc

# Add the repository to Apt sources:
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update

# Install the Docker packages
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin


# add user to docker group
# sudo usermod -aG docker $USER
echo Adding user to docker grup -----------------------------------------------------------------------------------
sudo usermod -aG docker sparrow

# install git
echo Installing git -----------------------------------------------------------------------------------
sudo apt install git -y

# Clone the repositor
echo Cloning repo -----------------------------------------------------------------------------------
# sudo git clone https://github.com/sparrowapp-dev/sparrow-api.git
sudo git clone -b feat/docker-setup https://github.com/sparrowapp-dev/sparrow-app.git

# cd into cloned directory.
echo cd into repo -----------------------------------------------------------------------------------
cd /sparrow-app

# Run docker-compose
echo Running docker-compose up -d -----------------------------------------------------------------------------------
docker-compose up -d

